### ISSUE TITLE
v1.1 BuddyPress database error

### ISSUE THREAD

**Issue by AndriusOrihive** [arbet/wordpress-linkedin-login#32]
After last update WordPress is showing an error:

`WordPress database error Table '[database name]wp_bp_xprofile_fields' doesn't exist for query SELECT id, name FROM `wp_bp_xprofile_fields` WHERE 1 made by do_action('admin_init'), WP_Hook->do_action, WP_Hook->apply_filters, PKLI_Settings->init_settings`

We are not using the BuddyPress plugin. Is it now necessary?

**Comment by arbet** [comment]
@AndriusOrihive - Buddypress is not a requirement for the plugin, thanks for reporting this. 

I'll get our developer to look into this - @annakuprina please handle.

**Comment by annakuprina** [comment]
Fixed this, I added the condition to check if the Buddypress is activated or not. Please update the plugin version to the latest one

**Comment by arbet** [comment]
@AndriusOrihive - I'm closing this. Please reopen if the issue persists.
