### ISSUE TITLE
Notified?

### ISSUE THREAD

**Issue by CaitNiHaonghusa** [arbet/wordpress-linkedin-login#37]
Hi, I have this plugin set up on my site and I'm just wondering will I be notified when someone logs in via LinkedIn and how does that work?

Thanks,
Katie

**Comment by arbet** [comment]
Hey Katie, 

You won't get any notification as this isn't a built in feature in the plugin. Try testing it with this plugin and see if it works: https://wordpress.org/plugins/wp-user-login-notifier/ (I don't promise it will as we haven't tested this)

--Samer

**Comment by affirmative-pl** [comment]
Hi,
I have tried this plugin but it doesn't work, there are no notifications
I have also tested this one, but no luck here too: https://wordpress.org/plugins/bnfw/
WordPress normally sends a "New User Registration" email to admin upon account creation. Logically it should do the same when an account is created by means of LinkedIn Integration.
Would you please consider looking into this, so admin gets notified of a new user account?
